remote_theme: poole/lanyon@v1.1.0  
plugins:
- jekyll-remote-theme
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-sitemap
defaults:
  - scope:
      path:            "*"
    values:
      sitemap:         false
